#!/usr/bin/perl

#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::Build::CreateLinks  qw(:all);

event_templates('nethserver-glpi-update', qw(
    /etc/httpd/conf.d/glpi.conf
    /etc/glpi/config_db.php
    /etc/httpd/conf.d/default-virtualhost.inc
    /etc/cron.d/glpi
));

event_actions('nethserver-glpi-update', qw(
  initialize-default-databases 00
   nethserver-glpi-conf 40
));

event_services('nethserver-glpi-update', qw(
   httpd reload
));

my $event = 'trusted-networks-modify';
templates2events("/etc/httpd/conf.d/glpi.conf", $event);
event_services($event, 'httpd' => 'reload');
