#!/usr/bin/perl

#
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Password;

unlink '/usr/share/glpi/install/install.php';

# check if glpi db exists
if ( -d '/var/lib/mysql/glpi' ) {
    exit 0;
}

# generate random db pass
my $db_pass = NethServer::Password::store('glpi');
my @file = glob "/usr/share/glpi/install/mysql/glpi-*-empty.sql";

open(my $fh, '|-', '/usr/bin/mysql -B') || die("[ERROR] Could not open mysql process");
print $fh qq(
create database glpi;
grant all privileges on glpi.* to 'glpi'\@'localhost' identified by '$db_pass';
flush privileges;
use glpi
source $file[0]
);
close ($fh) || die("[ERROR] glpi inventory DB initialization FAILED");

